export const tokens = {
  colors: {
    bg: '#FFFFFF',
    text: '#0B0B0B',
    muted: '#4B4B4B',
    panel: '#FFFFFF',
    panelSoft: 'rgba(255, 255, 255, 0.92)',
    border: '#000000',
    borderSoft: 'rgba(0, 0, 0, 0.12)',
    shadow: 'rgba(0, 0, 0, 0.12)',
    accent: '#FFE866',
    accentSoft: 'rgba(255, 232, 102, 0.35)',
    grid: 'rgba(0, 0, 0, 0.05)',
  },
  space: {
    xs: 8,
    sm: 12,
    md: 18,
    lg: 26,
    xl: 36,
  },
  radii: {
    sm: 12,
    md: 18,
    lg: 32,
    pill: 999,
  },
  stroke: {
    hairline: 1,
    regular: 2,
    strong: 3,
  },
  shadow: {
    card: 'none',
    overlay: 'none',
  },
  layout: {
    safeArea: {left: 80, right: 80, top: 60, bottom: 80},
    maxContentWidth: 1440,
  },
  storyboard: {
    canvasPadding: 96,
    cardShell: {
      maxWidth: 1680,
      borderRadius: 36,
      paddingY: 56,
      paddingX: 64,
      gridGap: 40,
      rightMinWidth: 420,
      leftFraction: 1.18,
      rightFraction: 0.82,
      eyebrowSize: 14,
      eyebrowMarginBottom: 18,
      titleSize: 68,
      titleMarginBottom: 16,
      titleLineHeight: 1.08,
      subtitleSize: 30,
      subtitleLineHeight: 1.35,
      subtitleMarginBottom: 24,
      subtitleMaxWidth: 1120,
    },
    codeBlock: {
      borderRadius: 20,
      headerPadY: 14,
      headerPadX: 16,
      headerFontSize: 14,
      bodyPadY: 16,
      linePadY: 3,
      linePadX: 16,
      lineNumberColWidth: 64,
      lineNumberFontSize: 17,
      codeFontSize: 17,
    },
    slide: {
      panelMaxWidth: 1440,
      panelPadY: 36,
      panelPadX: 48,
      panelRadius: 28,
      panelGridGap: 28,
      titleSize: 66,
      subtitleSize: 30,
      tableHeaderSize: 16,
      tableBodySize: 23,
      bodySize: 26,
      bulletSize: 28,
      fallbackKickerSize: 22,
      fallbackBodySize: 30,
    },
    explain: {
      gap: 24,
      listGap: 16,
      bodySize: 26,
      bodyLineHeight: 1.3,
    },
    chart: {
      panelMaxWidth: 1440,
      panelPadY: 36,
      panelPadX: 48,
      panelRadius: 28,
      eyebrowSize: 14,
      eyebrowMarginBottom: 12,
      titleSize: 66,
      titleMarginBottom: 22,
      titleLineHeight: 1.08,
      defaultWidth: 1360,
      defaultHeight: 620,
      columnGap: 22,
      minBarHeight: 10,
      barRadius: 16,
      labelSize: 24,
      labelLineHeight: 1.2,
    },
  },
} as const;
